# Generated by Django 2.0.13 on 2019-03-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_property_uuid_primary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Category',
        ),
    ]
