# Generated by Django 2.0.13 on 2019-04-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_set_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recurring_check_interval',
            field=models.CharField(blank=True, help_text='Number of months', max_length=7, null=True),
        ),
    ]
